name = "Lernisto Zen"
license = "MIT"
licenselink = "https://github.com/lernisto/lernisto-zen/blob/master/LICENSE.md"
description = "Lernisto Zen is a minimal hugo theme."
tags = ["blog"]
features = ["blog", "themes"]
min_version = 0.13

[author]
    name = "Terrel Shumway"
    homepage = "http://terrel.shumway.us/"
